server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://200.58.106.151:8084/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

spring:
  datasource:
    url: jdbc:postgresql://200.58.106.151:7799/capnee
    username: root
    password: dbpassuat
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true


security:
  jwt:
    secret-key: secret

micro:
  user:
    url: http://149.50.140.55:8081    

