server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

spring:
  cloud:
    gateway:
      routes:
        - id: academy-service
          uri: lb://academy-service
          predicates:
            - Path=/academy/**
          filters:
            - StripPrefix=1
            - name: RequestAuthFilter
              args:
                headerName: Authorization
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - name: RequestAuthFilter
              args:
                headerName: Authorization
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

authentication:
  server:
    url: lb://authentication-service